### ISSUE TITLE
[Android] data parcel size error crashing application

### ISSUE THREAD

**Issue by abhishekkale92** [diachedelic/capacitor-blob-writer#55]
We have use this plugin passing blob which is having data (1.3 Mb), though creating file successfully on my device but it crashing my application in between.

The file is gettting created post crashing the application as per log.
![tempsnip](https://user-images.githubusercontent.com/109076573/196900520-812e3c3c-354f-45ba-9d32-7807dd7343b2.png)

Detail log: 

2022-10-20 13:59:38.788 20203-20310 D/eglCodecCommon: setVertexArrayObject: set vao to 2 (2) 0 0
2022-10-20 13:59:42.554 20203-20333 V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 66914741, pluginId: BlobWriter, methodName: get_config
2022-10-20 13:59:42.557 20203-20333 V/Capacitor: callback: 66914741, pluginId: BlobWriter, methodName: get_config, methodData: {}
2022-10-20 13:59:42.574 20203-20333 V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 66914742, pluginId: Filesystem, methodName: getUri
2022-10-20 13:59:42.576 20203-20333 V/Capacitor: callback: 66914742, pluginId: Filesystem, methodName: getUri, methodData: {"path":"pdf_2022-10-20_13-59.pdf","directory":"DATA"}
2022-10-20 13:59:42.965 20203-20203 E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1202648)
2022-10-20 13:59:42.969 20203-20203 D/AndroidRuntime: Shutting down VM
2022-10-20 13:59:43.003 20203-20203 E/AndroidRuntime: FATAL EXCEPTION: main
    Process:, PID: 20203
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
        at android.app.Activity.startActivityForResult(Activity.java:4544)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
        at android.app.Activity.startActivity(Activity.java:4905)
        at android.app.Activity.startActivity(Activity.java:4873)
        at com.getcapacitor.Bridge.launchIntent(Bridge.java:274)
        at com.getcapacitor.BridgeWebViewClient.shouldOverrideUrlLoading(BridgeWebViewClient.java:27)
        at tY.a(PG:3)
        at xl.b(PG:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1202648 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1127)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3754)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
        at android.app.Activity.startActivityForResult(Activity.java:4586) 
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584) 
        at android.app.Activity.startActivityForResult(Activity.java:4544) 
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570) 
        at android.app.Activity.startActivity(Activity.java:4905) 
        at android.app.Activity.startActivity(Activity.java:4873) 
        at com.getcapacitor.Bridge.launchIntent(Bridge.java:274) 
        at com.getcapacitor.BridgeWebViewClient.shouldOverrideUrlLoading(BridgeWebViewClient.java:27) 
        at tY.a(PG:3) 
        at xl.b(PG:81) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2022-10-20 13:59:43.017 20203-20380 D/Capacitor/BlobWriter: OPTIONS /data/user/0/files/pdf_2022-10-20_13-59.pdf
2022-10-20 13:59:43.216 20203-20203 I/Process: Sending signal. PID: 20203 SIG: 9
2022-10-20 13:59:43.216 20203-20380 D/Capacitor/BlobWriter: PUT /data/user/0/files/pdf_2022-10-20_13-59.pdf

**Comment by diachedelic** [comment]
This plugin does not use remote procedure calls. I can only assume that this problem is caused by your application code.
